# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: https://hexo.io/icon/favicon-96x96.png

# avatar: images/logo.jpg
# banner_small: images/logo.jpg
# banner_large: images/banner-large.png
logo: https://lakerskayak.club/images/logo_small.jpg 
#

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  俱乐部介绍: about
  皮划艇项目: course
  日常活动: archives
  联系我们: contact
  English: en
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
#social:
  # github: https://github.com/GallenHu
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget1:
  title: 千岛湖湖人皮划艇俱乐部
  content: <p>地址：浙江省淳安县千岛湖镇滨湖路96号 <br>电话：15158019159 - 阿栋 <br>电话：13588360785 - 欧文</p> 

widget2:
  title: 友情链接
  content: <p><a href="https://www.americancanoe.org/" target="_blank">美国皮划艇协会网站（ACA）</a> <br> <a href="http://www.sdkc.org/" target="_blank">圣地亚哥皮划艇俱乐部网站</a></p>



footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> Theme by <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a> Hosted by <a href="https://pages.github.com/" target="_blank">Github Pages</a> Maintained by <a href="https://jenny42.com" target="_blank">jenny42</a>
